name: thermalnerfs
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.7.1
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-documentation=11.7.91
  - cuda-driver-dev=11.7.99
  - cuda-gdb=11.7.91
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.7.91
  - cuda-nsight=11.7.91
  - cuda-nsight-compute=11.7.1
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=11.7.91
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=11.7.101
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=11.7.101
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=11.7.91
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gds-tools=1.3.1.18
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.91
  - libcufile=1.8.1.2
  - libcufile-dev=1.3.1.18
  - libcurand=10.3.4.107
  - libcurand-dev=10.2.10.91
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - nsight-compute=2022.2.1.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.8.18
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - asttokens==2.4.1
      - backcall==0.2.0
      - comm==0.2.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dearpygui==1.11.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - docstring-parser==0.16
      - eval-type-backport==0.2.0
      - executing==2.0.1
      - fonttools==4.49.0
      - freqencoder==0.0.0
      - gridencoder==0.0.0
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.2
      - ipykernel==6.29.3
      - ipython==8.12.3
      - jedi==0.19.1
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-utilities==0.10.1
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - nvdiffrast==0.3.1
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pandas==2.0.3
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pymcubes==0.1.4
      - pymeshlab==2022.2.post3
      - pyparsing==3.1.1
      - python-dateutil==2.9.0
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyzmq==25.1.2
      - raymarching-mob==0.0.0
      - rich==13.7.1
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - shencoder==0.0.0
      - shtab==1.7.1
      - six==1.16.0
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.3.0
      - tifffile==2023.7.10
      - torch-efficient-distloss==0.1.3
      - torch-ema==0.3
      - torchmetrics==1.3.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.1
      - trimesh==4.1.7
      - tyro==0.8.11
      - tzdata==2024.1
      - wcwidth==0.2.13
      - xatlas==0.0.9
      - zipp==3.17.0
